<?php
use Casa\Adotivo;
use Casa\AdotivoLog;
use Illuminate\Database\Seeder;

class AdotivosTableSeeder extends Seeder 
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
	public function run() 
	{
    	$adotivos = [
    	    [
				'matricula'         => 'CASA-00000001',
    			'nome'              => 'Rodrigo Azevedo Dias',
    			'sexo'              => 'M',
    			'nascimento'        => '2008-10-10',
    			'data_chegada'      => '2008-12-12',
    			'data_adocao'       => null,
    			'nacionalidade_id'  => 1,
    			'instituicao_id'    => 2,
    			'usuario_id'        => 4,
    			'etnia_id'          => 1,
    			'status_id'         => 1,
    			'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000002',
	    		'nome'              => 'Isabelle Sousa Rodrigues',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2010-10-28',
	    		'data_chegada'      => '2010-12-01',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 2,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000003',
	    		'nome'              => 'Danilo Gomes Oliveira',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2013-07-13',
	    		'data_chegada'      => '2013-12-01',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 3,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000004',
	    		'nome'              => 'Vitoria Souza Silva',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-06-12',
	    		'data_chegada'      => '2016-12-01',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 4,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000005',
	    		'nome'              => 'Carolina Oliveira Correia',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-09-07',
	    		'data_chegada'      => '2016-11-07',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 5,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000006',
	    		'nome'              => 'Luis Castro Araujo',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2011-07-14',
	    		'data_chegada'      => '2011-08-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 6,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000007',
	    		'nome'              => 'Manuela Azevedo Sousa',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2012-06-10',
	    		'data_chegada'      => '2012-12-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 7,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000008',
	    		'nome'              => 'Luiza Costa Cavalcanti',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2014-06-02',
	    		'data_chegada'      => '2014-08-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000009',
	    		'nome'              => 'Paulo Silva Lima',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2014-12-17',
	    		'data_chegada'      => '2015-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05" 
    		],
    		[
				'matricula'         => 'CASA-00000010',
	    		'nome'              => 'Sophia Souza Dias',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-12-12',
	    		'data_chegada'      => '2017-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05" 
    		],
    		[
				'matricula'         => 'CASA-00000011',
	    		'nome'              => 'Murilo Araujo Alves',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2010-02-20',
	    		'data_chegada'      => '2010-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000012',
	    		'nome'              => 'Diogo Souza Gomes',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2010-07-20',
	    		'data_chegada'      => '2010-11-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000013',
    			'nome'              => 'Gabriel Cunha Araujo',
    			'sexo'              => 'M',
    			'nascimento'        => '2008-10-10',
    			'data_chegada'      => '2008-12-12',
    			'data_adocao'       => null,
    			'nacionalidade_id'  => 1,
    			'instituicao_id'    => 2,
    			'usuario_id'        => 4,
    			'etnia_id'          => 1,
    			'status_id'         => 2,
    			'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000014',
	    		'nome'              => 'Beatrice Pereira Almeida',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2010-10-28',
	    		'data_chegada'      => '2010-12-01',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 2,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05" 
    		],
    		[
				'matricula'         => 'CASA-00000015',
	    		'nome'              => 'Tomás Cardoso Dias',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2013-07-13',
	    		'data_chegada'      => '2013-12-01',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 3,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000016',
	    		'nome'              => 'Vitoria Souza Silva',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-06-12',
	    		'data_chegada'      => '2016-12-01',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 4,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05", 
    		],
    		[
				'matricula'         => 'CASA-00000017',
	    		'nome'              => 'Letícia Alves Castro',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-09-07',
	    		'data_chegada'      => '2016-11-07',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 5,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05" 
    		],
    		[
				'matricula'         => 'CASA-00000018',
	    		'nome'              => 'Gustavo Gomes Souza',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2011-07-14',
	    		'data_chegada'      => '2011-08-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 6,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000019',
	    		'nome'              => 'Cauã Cunha Ferreira',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2012-06-10',
	    		'data_chegada'      => '2012-12-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 7,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05", 
    		],
    		[
				'matricula'         => 'CASA-00000020',
	    		'nome'              => 'Vinícius Oliveira Lima',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2014-06-02',
	    		'data_chegada'      => '2014-08-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000021',
	    		'nome'              => 'Julian Oliveira Pinto',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2014-12-17',
	    		'data_chegada'      => '2015-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 3,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000022',
	    		'nome'              => 'Rafaela Rodrigues Goncalves',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-12-12',
	    		'data_chegada'      => '2017-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 3,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000023',
	    		'nome'              => 'Thaís Martins Gomes',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2010-02-20',
	    		'data_chegada'      => '2010-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id' => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 3,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000024',
	    		'nome'              => 'Fábio Melo Carvalho',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2010-07-20',
	    		'data_chegada'      => '2010-11-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 3,
	    		'created_at'        => "2017-09-05",
    		],
    		#new 2
    		[
				'matricula'         => 'CASA-00000025',
    			'nome'              => 'Beatriz Castro Santos',
    			'sexo'              => 'F',
    			'nascimento'        => '2000-10-10',
    			'data_chegada'      => '2000-12-12',
    			'data_adocao'       => null,
    			'nacionalidade_id'  => 1,
    			'instituicao_id'    => 2,
    			'usuario_id'        => 4,
    			'etnia_id'          => 1,
    			'status_id'         => 3,
    			'created_at'        => "2017-09-05", 
    		],
    		[
				'matricula'         => 'CASA-00000026',
	    		'nome'              => 'Carolina Dias Gomes',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2003-10-28',
	    		'data_chegada'      => '2003-12-01',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 2,
	    		'status_id'         => 2,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000027',
	    		'nome'              => 'Alice Barbosa Souza',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2005-07-13',
	    		'data_chegada'      => '2005-12-01',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 3,
	    		'status_id'         => 4,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000028',
	    		'nome'              => 'Mateus Alves Costa',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2006-06-12',
	    		'data_chegada'      => '2006-12-01',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 4,
	    		'status_id'         => 4,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000029',
	    		'nome'              => 'Gabriel Barros Oliveira',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2007-09-07',
	    		'data_chegada'      => '2010-11-07',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 5,
	    		'status_id'         => 4,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000030',
	    		'nome'              => 'Giovana Rodrigues Goncalves',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2000-12-14',
	    		'data_chegada'      => '2000-10-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 6,
	    		'status_id'         => 4,
	    		'created_at'        => "2017-09-05" 
    		],
    		[
				'matricula'         => 'CASA-00000031',
	    		'nome'              => 'Erick Almeida Souza',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2002-06-10',
	    		'data_chegada'      => '2002-12-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 7,
	    		'status_id'         => 4,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000032',
	    		'nome'              => 'Douglas Silva Almeida',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2012-06-02',
	    		'data_chegada'      => '2012-08-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 5,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000033',
	    		'nome'              => 'Amanda Silva Fernandes',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2004-12-17',
	    		'data_chegada'      => '2004-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 5,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000034',
	    		'nome'              => 'Nicolash Alves Barbosa',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2003-12-12',
	    		'data_chegada'      => '2005-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 5,
	    		'created_at'        => "2017-09-05", 
    		],
    		[
				'matricula'         => 'CASA-00000035',
	    		'nome'              => 'Danilo Barbosa Gomes',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2013-02-20',
	    		'data_chegada'      => '2013-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 5,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000036',
	    		'nome'              => 'Luiza Sousa Pinto',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2009-07-20',
	    		'data_chegada'      => '2009-11-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 6,
	    		'created_at'        => "2017-09-05",
    		],
    		#new 1
    		[
				'matricula'         => 'CASA-00000037',
    			'nome'              => 'Raissa Barbosa Cunha',
    			'sexo'              => 'F',
    			'nascimento'        => '2011-10-10',
    			'data_chegada'      => '2011-12-12',
    			'data_adocao'       => null,
    			'nacionalidade_id'  => 1,
    			'instituicao_id'    => 2,
    			'usuario_id'        => 4,
    			'etnia_id'          => 1,
    			'status_id'         => 6,
    			'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000038',
	    		'nome'              => 'Luan Correia Pinto',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2010-10-28',
	    		'data_chegada'      => '2010-12-01',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 2,
	    		'status_id'         => 6,
	    		'created_at'        => "2017-09-05", 
    		],
    		[
				'matricula'         => 'CASA-00000039',
	    		'nome'              => 'Gabrielle Ferreira Pinto',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2013-07-13',
	    		'data_chegada'      => '2013-12-01',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 3,
	    		'status_id'         => 6,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000040',
	    		'nome'              => 'Tiago Silva Ferreira',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2017-01-12',
	    		'data_chegada'      => '2017-01-20',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 4,
	    		'status_id'         => 6,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000041',
	    		'nome'              => 'João Ribeiro Souza',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2015-09-07',
	    		'data_chegada'      => '2015-11-07',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 5,
	    		'status_id'         => 6,
	    		'created_at'        => "2017-09-05", 
    		],
    		[
				'matricula'         => 'CASA-00000042',
	    		'nome'              => 'Gabrielly Martins Araujo',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2011-07-14',
	    		'data_chegada'      => '2011-08-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 6,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000043',
	    		'nome'              => 'Carolina Oliveira Correia',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2012-06-10',
	    		'data_chegada'      => '2012-12-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 7,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000044',
	    		'nome'              => 'Rafaela Santos Cardoso',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2014-06-02',
	    		'data_chegada'      => '2014-08-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000045',
	    		'nome'              => 'Isabelle Barbosa Lima',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2014-12-17',
	    		'data_chegada'      => '2015-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000046',
	    		'nome'              => 'Sarah Araujo Pereira',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-12-12',
	    		'data_chegada'      => '2017-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05", 
    		],
    		[
				'matricula'         => 'CASA-00000047',
	    		'nome'              => 'Yasmin Correia Barbosa',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2010-02-20',
	    		'data_chegada'      => '2010-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000048',
	    		'nome'              => 'Fábio Melo Castro',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2010-07-20',
	    		'data_chegada'      => '2010-11-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000049',
	    		'nome'              => 'Victor Cardoso Sousa',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2013-02-20',
	    		'data_chegada'      => '2013-02-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05",
    		],
    		[
				'matricula'         => 'CASA-00000050',
	    		'nome'              => 'Raissa Rodrigues Fernandes',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2010-07-20',
	    		'data_chegada'      => '2010-11-25',
	    		'data_adocao'       => null,
	    		'nacionalidade_id'  => 1,
	    		'instituicao_id'    => 2,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => "2017-09-05",
    		]
    	];
		DB::table('adotivos')->insert($adotivos);
		# Gerar logs.
		foreach(Adotivo::all() as $adotivo) {
			$log = new AdotivoLog();
			$log->setAll($adotivo, $adotivo->created_at);
			$log->salvar();
		}
    }
}
