<?php

use Illuminate\Database\Seeder;

class AdotantesTableSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    # CPF repetido 204.755.783-68
    public function run() {
        $adotantes = [
        	[
        		'nome'            => 'Adriane Santiago de Silva',
        		'conjuge_nome'    => 'Gustavo Felipe da Silva',
        		'sexo'            => 'F',
        		'nascimento'      => '1997-09-05',
        		'cpf'             => '714.498.503-59',
        		'rg'              => '41.555.400-9',
        		'endereco'        => 'Avenida Florianópolis',
        		'endereco_numero' => '260',
        		'complemento'     => 'Ao lado Correios',
        		'cep'             => '68906-142',
        		'bairro'          => 'Cabralzinho',
        		'cidade'          => 'Macapá',
        		'telefone'        => '(96) 2514-3242',
        		'celular'         => '(96) 99118-1553',
        		'email'           => 'adriane97@hotmail.com',
        		'estado_id'       =>  5,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      => date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Melissa Barcelos',
        		'conjuge_nome'    => '',
        		'sexo'            => 'F',
        		'nascimento'      => '1980-06-10',
        		'cpf'             => '331.648.536-88',
        		'rg'              => '41.555.401-9',
        		'endereco'        => 'Avenida João Gomes',
        		'endereco_numero' => '3600',
        		'complemento'     => 'Apartamento 106',
        		'cep'             => '67120-451',
        		'bairro'          => 'Vila Renato',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'melissa_barcellos@hotmail.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  1,
        		'instituicao_id'  =>  2,
        		'created_at'      => date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
			    [
        		'nome'            => 'Fernando Silva Prado',
        		'conjuge_nome'    => 'Maria do Socorro Prado',
        		'sexo'            => 'M',
        		'nascimento'      => '1975-12-03',
        		'cpf'             => '482.278.560-20',
        		'rg'              => '41.555.402-9',
        		'endereco'        => 'Rua 27 de Outubro',
        		'endereco_numero' => '5A',
        		'complemento'     => 'Casa 2',
        		'cep'             => '97120-451',
        		'bairro'          => 'Pirituba',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'fernando@hotmail.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      => date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Bento de Albuquerque Santiago',
        		'conjuge_nome'    => 'Maria Capitolina Santiago',
        		'sexo'            => 'M',
        		'nascimento'      => '1970-01-03',
        		'cpf'             => '337.107.585-05',
        		'rg'              => '41.555.403-9',
        		'endereco'        => 'Rua das Rosas',
        		'endereco_numero' => '176',
        		'complemento'     => '',
        		'cep'             => '97120-451',
        		'bairro'          => 'Jardim Santo Eduardo',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'santiago@hotmail.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      => date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Pedro Costa Lima',
        		'conjuge_nome'    => 'Renata Juliana ',
        		'sexo'            => 'M',
        		'nascimento'      => '1981-06-06',
        		'cpf'             => '577.115.635-31',
        		'rg'              => '41.555.404-9',
        		'endereco'        => 'Rua Felipe Smith',
        		'endereco_numero' => '6C',
        		'complemento'     => 'Rua sem saída',
        		'cep'             => '97120-451',
        		'bairro'          => 'Jardim da Luz',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'pedro_costa@hotmail.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Mariana Cecília Ribeiro',
        		'conjuge_nome'    => 'João Ferreira Ribeiro Alves',
        		'sexo'            => 'F',
        		'nascimento'      => '1985-06-06',
        		'cpf'             => '167.401.588-78',
        		'rg'              => '41.555.405-9',
        		'endereco'        => 'Rua Nova Paulista',
        		'endereco_numero' => '104',
        		'complemento'     => 'Rua sem saída',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Mirante',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'mariana@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Juliana Catarina Cecília Ribeiro',
        		'conjuge_nome'    => 'Ricardo Lopes Ribeiro ',
        		'sexo'            => 'F',
        		'nascimento'      => '1985-06-06',
        		'cpf'             => '623.163.262-85',
        		'rg'              => '41.555.406-9',
        		'endereco'        => 'Rua Nova Paulista',
        		'endereco_numero' => '104',
        		'complemento'     => 'Rua sem saída',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Mirante',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'ricardo05@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Sônia Fernades Silva',
        		'conjuge_nome'    => 'Ricardo Lopes Fernades',
        		'sexo'            => 'F',
        		'nascimento'      => '1990-06-06',
        		'cpf'             => '654.381.655-48',
        		'rg'              => '41.555.407-9',
        		'endereco'        => 'Rua Tomás Gomes',
        		'endereco_numero' => '200',
        		'complemento'     => 'Casa 1',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Leopoldina',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'sonia_lopes@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Luciano Fabiano Lima',
        		'conjuge_nome'    => 'Maria da Dores Lima',
        		'sexo'            => 'M',
        		'nascimento'      => '1986-06-06',
        		'cpf'             => '764.436.429-37',
        		'rg'              => '41.555.408-9',
        		'endereco'        => 'Rua Tomás Gomes',
        		'endereco_numero' => '187',
        		'complemento'     => 'Casa 2',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Lapa',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'luciano@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Fabiana de Paula Alves',
        		'conjuge_nome'    => 'Bruno de Gomes Alves',
        		'sexo'            => 'F',
        		'nascimento'      => '1969-06-06',
        		'cpf'             => '024.315.324-45',
        		'rg'              => '41.555.409-9',
        		'endereco'        => 'Rua Tomás Gomes',
        		'endereco_numero' => '187',
        		'complemento'     => 'Casa 2',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Lapa',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'fabiana@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Adriana Lima Ferreira',
        		'conjuge_nome'    => 'Gustavo Lima da Costa',
        		'sexo'            => 'F',
        		'nascimento'      => '1975-06-06',
        		'cpf'             => '882.366.563-90',
        		'rg'              => '41.555.410-9',
        		'endereco'        => 'Rua Tomás Gomes',
        		'endereco_numero' => '200',
        		'complemento'     => 'Casa 2',
        		'cep'             => '97120-451',
        		'bairro'          => 'Pirituba',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'adriana@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Maria de Silva Costa Lima',
        		'conjuge_nome'    => 'Gustavo Felipe da Lima',
        		'sexo'            => 'F',
        		'nascimento'      => '1995-09-05',
        		'cpf'             => '137.655.338-40',
        		'rg'              => '41.555.411-9',
        		'endereco'        => 'Avenida Florianópolis',
        		'endereco_numero' => '260',
        		'complemento'     => 'Ao lado Correios',
        		'cep'             => '68906-142',
        		'bairro'          => 'Cabralzinho',
        		'cidade'          => 'Macapá',
        		'telefone'        => '(96) 2514-3242',
        		'celular'         => '(96) 99118-1553',
        		'email'           => 'maria95@hotmail.com',
        		'estado_id'       =>  5,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      => date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Juliana Pereira da Costa',
        		'conjuge_nome'    => '',
        		'sexo'            => 'F',
        		'nascimento'      => '1980-06-10',
        		'cpf'             => '822.003.952-30',
        		'rg'              => '41.555.412-9',
        		'endereco'        => 'Avenida João Gomes',
        		'endereco_numero' => '3600',
        		'complemento'     => 'Apartamento 106',
        		'cep'             => '67120-451',
        		'bairro'          => 'Vila Renato',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'juliana_pereira@hotmail.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  1,
        		'instituicao_id'  =>  2,
        		'created_at'      => date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
			    [
        		'nome'            => 'Renato Luís da Silva',
        		'conjuge_nome'    => 'Maria do Santana Silva',
        		'sexo'            => 'M',
        		'nascimento'      => '1989-12-03',
        		'cpf'             => '877.911.878-09',
        		'rg'              => '41.555.413-9',
        		'endereco'        => 'Rua 1 de Outubro',
        		'endereco_numero' => '7A',
        		'complemento'     => 'Casa 2',
        		'cep'             => '97120-451',
        		'bairro'          => 'Pirituba',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'fernando@hotmail.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      => date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Katia Ferreira Silvado',
        		'conjuge_nome'    => 'Thiago Santiago Silvado',
        		'sexo'            => 'F',
        		'nascimento'      => '1970-01-03',
        		'cpf'             => '715.369.741-10',
        		'rg'              => '41.555.414-9',
        		'endereco'        => 'Rua das Rosas',
        		'endereco_numero' => '176',
        		'complemento'     => '',
        		'cep'             => '97120-451',
        		'bairro'          => 'Jardim Santo Eduardo',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'katia@ygmail.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      => date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Felipe Almeida Silva',
        		'conjuge_nome'    => 'Renata Juliana Silva',
        		'sexo'            => 'M',
        		'nascimento'      => '1972-06-06',
        		'cpf'             => '373.047.581-98',
        		'rg'              => '41.555.415-9',
        		'endereco'        => 'Rua Felipe Smith',
        		'endereco_numero' => '6C',
        		'complemento'     => 'Rua sem saída',
        		'cep'             => '97120-451',
        		'bairro'          => 'Jardim da Luz',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'felipe_almeida@hotmail.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Milena Maria Silvado',
        		'conjuge_nome'    => 'Ricardo Silvado Ribeiro ',
        		'sexo'            => 'F',
        		'nascimento'      => '1987-06-06',
        		'cpf'             => '109.831.533-29',
        		'rg'              => '41.555.416-9',
        		'endereco'        => 'Rua Nova Paulista',
        		'endereco_numero' => '104',
        		'complemento'     => 'Rua sem saída',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Mirante',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'milena05@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Amanda Thais Vicente',
        		'conjuge_nome'    => 'Ricardo Lopes Vicente',
        		'sexo'            => 'F',
        		'nascimento'      => '1980-06-06',
        		'cpf'             => '365.252.251-67',
        		'rg'              => '41.555.417-9',
        		'endereco'        => 'Rua Nova Paulista',
        		'endereco_numero' => '104',
        		'complemento'     => 'Rua sem saída',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Mirante',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'amanda@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Janaina Silva da Costa',
        		'conjuge_nome'    => 'Ricardo Silva da Costa',
        		'sexo'            => 'F',
        		'nascimento'      => '1991-06-11',
        		'cpf'             => '377.425.178-92',
        		'rg'              => '41.555.418-9',
        		'endereco'        => 'Rua Tomás Gomes',
        		'endereco_numero' => '200',
        		'complemento'     => 'Casa 1',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Leopoldina',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'janaina_silva@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Viviane Solange',
        		'conjuge_nome'    => 'Felipe Mariano Costa',
        		'sexo'            => 'F',
        		'nascimento'      => '1986-06-06',
        		'cpf'             => '683.035.133-20',
        		'rg'              => '41.555.419-9',
        		'endereco'        => 'Rua Tomás Gomes',
        		'endereco_numero' => '187',
        		'complemento'     => 'Casa 2',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Lapa',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'viviane@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Andreia Almeida Silva',
        		'conjuge_nome'    => 'João Costa Silva Lima',
        		'sexo'            => 'F',
        		'nascimento'      => '1969-06-06',
        		'cpf'             => '340.556.700-95',
        		'rg'              => '41.555.420-9',
        		'endereco'        => 'Rua Tomás Gomes',
        		'endereco_numero' => '187',
        		'complemento'     => 'Casa 2',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Lapa',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'andreia_silva@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Luisa Ferreira Braga',
        		'conjuge_nome'    => 'Gustavo Lima da Braga',
        		'sexo'            => 'F',
        		'nascimento'      => '1975-06-06',
        		'cpf'             => '537.008.471-81',
        		'rg'              => '41.555.422-9',
        		'endereco'        => 'Rua Tomás Gomes',
        		'endereco_numero' => '200',
        		'complemento'     => 'Casa 2',
        		'cep'             => '97120-451',
        		'bairro'          => 'Pirituba',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'adriana@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	# new
        	[
        		'nome'            => 'Pedro Lima Silva',
        		'conjuge_nome'    => 'Mariana Katia Silvado',
        		'sexo'            => 'M',
        		'nascimento'      => '1995-09-05',
        		'cpf'             => '109.122.049-23',
        		'rg'              => '41.555.423-9',
        		'endereco'        => 'Avenida Florianópolis',
        		'endereco_numero' => '260',
        		'complemento'     => 'Ao lado Correios',
        		'cep'             => '68906-142',
        		'bairro'          => 'Cabralzinho',
        		'cidade'          => 'Macapá',
        		'telefone'        => '(96) 2514-3242',
        		'celular'         => '(96) 99118-1553',
        		'email'           => 'pedro95@hotmail.com',
        		'estado_id'       =>  5,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'                        => date('Y-m-d'),
            'escolaridade_id'                   => 5,
            'nascionalidade_id'                 => 1,
            'categoria_profissional_id'         => 4,
            'conjuge_escolaridade_id'           => 5,
            'conjuge_nascionalidade_id'         => 1,
            'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Zelia Novaes',
        		'conjuge_nome'    => '',
        		'sexo'            => 'F',
        		'nascimento'      => '1980-06-10',
        		'cpf'             => '934.582.125-23',
        		'rg'              => '41.555.424-9',
        		'endereco'        => 'Avenida João Gomes',
        		'endereco_numero' => '3600',
        		'complemento'     => 'Apartamento 106',
        		'cep'             => '67120-451',
        		'bairro'          => 'Vila Renato',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'zelia_novaes@hotmail.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  1,
        		'instituicao_id'  =>  2,
        		'created_at'      => date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
			    [
        		'nome'            => 'Julia Ferraz de Nova',
        		'conjuge_nome'    => 'Thiago Ferraz de Nova',
        		'sexo'            => 'F',
        		'nascimento'      => '1989-12-03',
        		'cpf'             => '384.733.305-44',
        		'rg'              => '41.555.425-9',
        		'endereco'        => 'Rua 1 de Outubro',
        		'endereco_numero' => '7A',
        		'complemento'     => 'Casa 2',
        		'cep'             => '97120-451',
        		'bairro'          => 'Pirituba',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'juliana@hotmail.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      => date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Bruna Miranda Lima',
        		'conjuge_nome'    => 'Thiago Miranda Lima',
        		'sexo'            => 'F',
        		'nascimento'      => '1970-01-03',
        		'cpf'             => '452.332.246-58',
        		'rg'              => '41.555.426-9',
        		'endereco'        => 'Rua das Rosas',
        		'endereco_numero' => '176',
        		'complemento'     => '',
        		'cep'             => '97120-451',
        		'bairro'          => 'Jardim Santo Eduardo',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'bruna@gmail.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      => date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Gustavo Novaes Lima',
        		'conjuge_nome'    => 'Renata Novaes Lima',
        		'sexo'            => 'M',
        		'nascimento'      => '1972-06-06',
        		'cpf'             => '901.675.572-11',
        		'rg'              => '41.555.427-9',
        		'endereco'        => 'Rua Felipe Smith',
        		'endereco_numero' => '6C',
        		'complemento'     => 'Rua sem saída',
        		'cep'             => '97120-451',
        		'bairro'          => 'Jardim da Luz',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'gustavo@hotmail.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Gabriela Lucas de Santiago',
        		'conjuge_nome'    => 'Ricardo Silvado Ribeiro ',
        		'sexo'            => 'F',
        		'nascimento'      => '1987-06-06',
        		'cpf'             => '656.416.256-12',
        		'rg'              => '477.249.228-46',
        		'endereco'        => 'Rua Nova Paulista',
        		'endereco_numero' => '104',
        		'complemento'     => 'Rua sem saída',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Mirante',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'milena05@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Tereza Mariana',
        		'conjuge_nome'    => 'João Lopes Vicente',
        		'sexo'            => 'F',
        		'nascimento'      => '1980-06-06',
        		'cpf'             => '241.432.877-06',
        		'rg'              => '41.555.429-9',
        		'endereco'        => 'Rua Nova Paulista',
        		'endereco_numero' => '104',
        		'complemento'     => 'Rua sem saída',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Mirante',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'tereza@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Bianca Lima da Silva',
        		'conjuge_nome'    => 'Gustavo Silva da Costa',
        		'sexo'            => 'F',
        		'nascimento'      => '1991-06-11',
        		'cpf'             => '252.194.921-36',
        		'rg'              => '41.555.430-9',
        		'endereco'        => 'Rua Tomás Gomes',
        		'endereco_numero' => '200',
        		'complemento'     => 'Casa 1',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Leopoldina',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'janaina_silva@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Cintia Fernada da Silva',
        		'conjuge_nome'    => 'Felipe da Silva',
        		'sexo'            => 'F',
        		'nascimento'      => '1986-06-06',
        		'cpf'             => '036.672.741-90',
        		'rg'              => '41.555.431-9',
        		'endereco'        => 'Rua Tomás Gomes',
        		'endereco_numero' => '187',
        		'complemento'     => 'Casa 2',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Lapa',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'viviane@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Luana Bianca Silvado',
        		'conjuge_nome'    => 'João Costa Silvado',
        		'sexo'            => 'F',
        		'nascimento'      => '1969-06-06',
        		'cpf'             => '450.118.448-54',
        		'rg'              => '41.555.432-9',
        		'endereco'        => 'Rua Tomás Gomes',
        		'endereco_numero' => '187',
        		'complemento'     => 'Casa 2',
        		'cep'             => '97120-451',
        		'bairro'          => 'Vila Lapa',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'luana@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	],
        	[
        		'nome'            => 'Leonora Carlar Lima',
        		'conjuge_nome'    => 'Marcelo Santiago Lima Gomes',
        		'sexo'            => 'F',
        		'nascimento'      => '1975-06-06',
        		'cpf'             => '537.008.471-81',
        		'rg'              => '41.555.433-9',
        		'endereco'        => 'Rua Tomás Gomes',
        		'endereco_numero' => '200',
        		'complemento'     => 'Casa 2',
        		'cep'             => '97120-451',
        		'bairro'          => 'Pirituba',
        		'cidade'          => 'São Paulo',
        		'telefone'        => '(96) 2514-0000',
        		'celular'         => '(96) 99118-7654',
        		'email'           => 'leonora@yahoo.com',
        		'estado_id'       =>  1,
        		'usuario_id'      =>  4,
        		'estado_civil_id' =>  2,
        		'instituicao_id'  =>  2,
        		'created_at'      =>  date('Y-m-d'),

                'escolaridade_id'                   => 5,
                'nascionalidade_id'                 => 1,
                'categoria_profissional_id'         => 4,

                'conjuge_escolaridade_id'           => 5,
                'conjuge_nascionalidade_id'         => 1,
                'conjuge_categoria_profissional_id' => 4
        	]
        ];
        DB::table('adotantes')->insert($adotantes);
    }
}
