<?php

use Illuminate\Database\Seeder;

class AdotivosTableSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
    	$adotivos = [
    	    [
    			'nome'              => 'Rodrigo Azevedo Dias',
    			'sexo'              => 'M',
    			'nascimento'        => '2008-10-10',
    			'data_chegada'      => '2008-12-12',
    			'data_adocao'       => null,
    			'nascionalidade_id' => 1,
    			'instituicao_id'    => 1,
    			'usuario_id'        => 4,
    			'etnia_id'          => 1,
    			'status_id'         => 1,
    			'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Isabelle Sousa Rodrigues',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2010-10-28',
	    		'data_chegada'      => '2010-12-01',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 2,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Danilo Gomes Oliveira',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2013-07-13',
	    		'data_chegada'      => '2013-12-01',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 3,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Vitoria Souza Silva',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-06-12',
	    		'data_chegada'      => '2016-12-01',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 4,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Carolina Oliveira Correia',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-09-07',
	    		'data_chegada'      => '2016-11-07',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 5,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Luis Castro Araujo',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2011-07-14',
	    		'data_chegada'      => '2011-08-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 6,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Manuela Azevedo Sousa',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2012-06-10',
	    		'data_chegada'      => '2012-12-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 7,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Luiza Costa Cavalcanti',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2014-06-02',
	    		'data_chegada'      => '2014-08-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Paulo Silva Lima',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2014-12-17',
	    		'data_chegada'      => '2015-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Sophia Souza Dias',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-12-12',
	    		'data_chegada'      => '2017-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Murilo Araujo Alves',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2010-02-20',
	    		'data_chegada'      => '2010-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Diogo Souza Gomes',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2010-07-20',
	    		'data_chegada'      => '2010-11-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		#new 1
    		[
    			'nome'              => 'Gabriel Cunha Araujo',
    			'sexo'              => 'M',
    			'nascimento'        => '2008-10-10',
    			'data_chegada'      => '2008-12-12',
    			'data_adocao'       => null,
    			'nascionalidade_id' => 1,
    			'instituicao_id'    => 1,
    			'usuario_id'        => 4,
    			'etnia_id'          => 1,
    			'status_id'         => 2,
    			'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Beatrice Pereira Almeida',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2010-10-28',
	    		'data_chegada'      => '2010-12-01',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 2,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Tomás Cardoso Dias',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2013-07-13',
	    		'data_chegada'      => '2013-12-01',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 3,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Vitoria Souza Silva',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-06-12',
	    		'data_chegada'      => '2016-12-01',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 4,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Letícia Alves Castro',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-09-07',
	    		'data_chegada'      => '2016-11-07',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 5,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Gustavo Gomes Souza',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2011-07-14',
	    		'data_chegada'      => '2011-08-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 6,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Cauã Cunha Ferreira',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2012-06-10',
	    		'data_chegada'      => '2012-12-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 7,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Vinícius Oliveira Lima',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2014-06-02',
	    		'data_chegada'      => '2014-08-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Julian Oliveira Pinto',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2014-12-17',
	    		'data_chegada'      => '2015-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 3,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Rafaela Rodrigues Goncalves',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-12-12',
	    		'data_chegada'      => '2017-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 3,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Thaís Martins Gomes',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2010-02-20',
	    		'data_chegada'      => '2010-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 3,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Fábio Melo Carvalho',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2010-07-20',
	    		'data_chegada'      => '2010-11-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 3,
	    		'created_at'        => date('Y-m-d') 
    		],
    		#new 2
    		[
    			'nome'              => 'Beatriz Castro Santos',
    			'sexo'              => 'F',
    			'nascimento'        => '2000-10-10',
    			'data_chegada'      => '2000-12-12',
    			'data_adocao'       => null,
    			'nascionalidade_id' => 1,
    			'instituicao_id'    => 1,
    			'usuario_id'        => 4,
    			'etnia_id'          => 1,
    			'status_id'         => 3,
    			'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Carolina Dias Gomes',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2003-10-28',
	    		'data_chegada'      => '2003-12-01',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 2,
	    		'status_id'         => 2,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Alice Barbosa Souza',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2005-07-13',
	    		'data_chegada'      => '2005-12-01',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 3,
	    		'status_id'         => 4,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Mateus Alves Costa',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2006-06-12',
	    		'data_chegada'      => '2006-12-01',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 4,
	    		'status_id'         => 4,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Gabriel Barros Oliveira',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2007-09-07',
	    		'data_chegada'      => '2010-11-07',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 5,
	    		'status_id'         => 4,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Giovana Rodrigues Goncalves',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2000-12-14',
	    		'data_chegada'      => '2000-10-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 6,
	    		'status_id'         => 4,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Erick Almeida Souza',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2002-06-10',
	    		'data_chegada'      => '2002-12-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 7,
	    		'status_id'         => 4,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Douglas Silva Almeida',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2012-06-02',
	    		'data_chegada'      => '2012-08-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 5,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Amanda Silva Fernandes',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2004-12-17',
	    		'data_chegada'      => '2004-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 5,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Nicolash Alves Barbosa',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2003-12-12',
	    		'data_chegada'      => '2005-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 5,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Danilo Barbosa Gomes',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2013-02-20',
	    		'data_chegada'      => '2013-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 5,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Luiza Sousa Pinto',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2009-07-20',
	    		'data_chegada'      => '2009-11-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 6,
	    		'created_at'        => date('Y-m-d') 
    		],
    		#new 1
    		[
    			'nome'              => 'Raissa Barbosa Cunha',
    			'sexo'              => 'F',
    			'nascimento'        => '2011-10-10',
    			'data_chegada'      => '2011-12-12',
    			'data_adocao'       => null,
    			'nascionalidade_id' => 1,
    			'instituicao_id'    => 1,
    			'usuario_id'        => 4,
    			'etnia_id'          => 1,
    			'status_id'         => 6,
    			'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Luan Correia Pinto',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2010-10-28',
	    		'data_chegada'      => '2010-12-01',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 2,
	    		'status_id'         => 6,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Gabrielle Ferreira Pinto',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2013-07-13',
	    		'data_chegada'      => '2013-12-01',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 3,
	    		'status_id'         => 6,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Tiago Silva Ferreira',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2017-01-12',
	    		'data_chegada'      => '2017-01-20',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 4,
	    		'status_id'         => 6,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'João Ribeiro Souza',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2015-09-07',
	    		'data_chegada'      => '2015-11-07',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 5,
	    		'status_id'         => 6,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Gabrielly Martins Araujo',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2011-07-14',
	    		'data_chegada'      => '2011-08-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 6,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Carolina Oliveira Correia',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2012-06-10',
	    		'data_chegada'      => '2012-12-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 7,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Rafaela Santos Cardoso',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2014-06-02',
	    		'data_chegada'      => '2014-08-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Isabelle Barbosa Lima',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2014-12-17',
	    		'data_chegada'      => '2015-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Sarah Araujo Pereira',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2016-12-12',
	    		'data_chegada'      => '2017-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Yasmin Correia Barbosa',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2010-02-20',
	    		'data_chegada'      => '2010-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Fábio Melo Castro',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2010-07-20',
	    		'data_chegada'      => '2010-11-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Victor Cardoso Sousa',
	    		'sexo'              => 'M',
	    		'nascimento'        => '2013-02-20',
	    		'data_chegada'      => '2013-02-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		],
    		[
	    		'nome'              => 'Raissa Rodrigues Fernandes',
	    		'sexo'              => 'F',
	    		'nascimento'        => '2010-07-20',
	    		'data_chegada'      => '2010-11-25',
	    		'data_adocao'       => null,
	    		'nascionalidade_id' => 1,
	    		'instituicao_id'    => 1,
	    		'usuario_id'        => 4,
	    		'etnia_id'          => 1,
	    		'status_id'         => 1,
	    		'created_at'        => date('Y-m-d') 
    		]
    	];
    	DB::table('adotivos')->insert($adotivos);
    }
}
